jmunta-tlx/repo-sync-dest-test1@main:
  - modules/module1/
  - modules/module2/

jmunta-tlx/repo-sync-dest-test2@main:
  - modules/module3/
  - modules/module4/

jmunta-tlx/repo-sync-dest-test3@main:
  - modules/module1/
  - modules/module5/
